mode: "grid_search"
training:
  epochs: 2
  batch_size: 4 # [4, 8, 16, 32]
  scale: 4
  low_res: 64
  sample_interval: 500

optimizer:
  learning_rate: 0.0002 #[0.005, 0.001, 0.0005, 0.0002, 0.00005]
  momentum: 0.5 #[0.3, 0.5, 0.7]

model:
  n_residual_blocks: [4, 8, 16, 32]
  g_filters: [16, 32, 64, 128]
  d_filters: [16, 32, 64, 128]

data:
  base_dir: "/home/begood/git/datasets"
  dataset: "coco_test"
  datasubset: "val2017"

checkpoint:
  dir: "checkpoints"
  max_to_keep: 3

tensorboard: # https://keras.io/api/callbacks/tensorboard/
  log_dir: logs
  write_graph: False
  write_images: False
  update_freq: 100
  profile_batch: 0